server:
  servlet:
    context-path: /
  port: 8085
application:
  name: market
logging:
  level:
    com.example: info
  file:
    log/market.log
market:
  exchanges:
#交易所
    wbfex-crtusdt:
      uris:
        uriCreateOrder: https://openapi.wbfex.com/open/api/create_order
        uriCancelOrder: https://openapi.wbfex.com/open/api/cancel_order
      symbol: CRTUSDT
#密钥
      sellpriKey: 6b03f98a58ee1199de8044a4dafe6416
      sellpubKey: 4ec466b39dc464cbcf6a797974be4ebb
      buypriKey: f214f884a1e3da2a1120a760e41c3a97
      buypubKey: 283bec1cb2808899e81e4680b184d161
#等待时间
      waitTimes: 1900
#价格基础价
      sellBasePrice: 0.07139
      buyBasePrice: 0.07
#价格浮动
      buyfluctuate: 10
      sellfluctuate: 6
#价格精度
      priceScale: 6
#数量基数
      buyamount: 120
      sellAmount: 285
#数量浮动
      amountFluctuate: 50
#买单占比
      buyOrderRatio: 4
      buyType: BUY
      sellType: SELL
      stopBuy: false
      stopSell: false
